### PR TITLE
Check if Parsec was indeed used

### LINKED ISSUE #19: Check on the CI that Parsec is actually called
If something went wrong with the SE driver registration, it is possible that Mbed Crypto is called for crypto operations instead of Parsec. We should check that Parsec is actually called.
This could be done via `./parsec-tool list-keys` checking that the result is not empty.

### PR DESCRIPTION
**Pull request by hug-dev**
by checking the mappings folder.
Fix #19

### CODE REVIEW

**Comment by hug-dev** [comment]
On a successfull run:
```
2021-03-04T11:26:42.9758105Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:42.9759113Z [INFO  parsec_service::front::front_end] New request received without authentication
2021-03-04T11:26:42.9760031Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:42.9760888Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:42.9761758Z [TRACE parsec_service::providers::core] list_authenticators ingress
2021-03-04T11:26:42.9762690Z [TRACE parsec_service::back::backend_handler] list_authenticators egress
2021-03-04T11:26:42.9763570Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:42.9764393Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:42.9765312Z [INFO  parsec_service::front::front_end] Response sent back from request without authentication
2021-03-04T11:26:42.9766113Z [TRACE parsec] handle_request egress
2021-03-04T11:26:42.9856053Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:42.9856854Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:42.9857640Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:42.9858371Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:42.9859109Z [TRACE parsec_service::providers::core] list_providers ingress
2021-03-04T11:26:42.9859815Z [TRACE parsec_service::back::backend_handler] list_providers egress
2021-03-04T11:26:42.9860755Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:42.9861460Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:42.9862215Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:42.9862846Z [TRACE parsec] handle_request egress
2021-03-04T11:26:42.9956545Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:42.9959447Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:42.9960262Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:42.9961019Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:42.9961880Z [TRACE parsec_service::providers::tpm] psa_generate_key ingress
2021-03-04T11:26:43.0880045Z [WARN  parsec_service::key_info_managers::on_disk_manager] Saving Key Triple (Application Name: "0", Provider ID: Tpm, Key Name: "parsec-se-driver-key1") mapping to disk.
2021-03-04T11:26:43.0881348Z [TRACE parsec_service::back::backend_handler] psa_generate_key egress
2021-03-04T11:26:43.0882178Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:43.0882968Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:43.0883799Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:43.0884530Z [TRACE parsec] handle_request egress
2021-03-04T11:26:43.0976072Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:43.0976853Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:43.0977618Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:43.0978346Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:43.0979050Z [TRACE parsec_service::providers::tpm] psa_export_public_key ingress
2021-03-04T11:26:43.1397883Z [TRACE parsec_service::back::backend_handler] psa_export_public_key egress
2021-03-04T11:26:43.1398985Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:43.1399788Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:43.1400617Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:43.1401356Z [TRACE parsec] handle_request egress
2021-03-04T11:26:43.1484106Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:43.1484886Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:43.1485651Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:43.1486364Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:43.1487053Z [TRACE parsec_service::providers::tpm] psa_sign_hash ingress
2021-03-04T11:26:43.1493150Z [TRACE parsec_service::back::backend_handler] psa_sign_hash egress
2021-03-04T11:26:43.1493937Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:43.1494626Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:43.1495364Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:43.1495995Z [TRACE parsec] handle_request egress
2021-03-04T11:26:43.1581444Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:43.1582227Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:43.1582991Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:43.1583741Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:43.1584429Z [TRACE parsec_service::providers::tpm] psa_verify_hash ingress
2021-03-04T11:26:43.2004475Z [TRACE parsec_service::back::backend_handler] psa_verify_hash egress
2021-03-04T11:26:43.2006235Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:43.2007105Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:43.2007945Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:43.2008691Z [TRACE parsec] handle_request egress
2021-03-04T11:26:43.2093279Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T11:26:43.2095517Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T11:26:43.2096287Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T11:26:43.2097011Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T11:26:43.2097705Z [TRACE parsec_service::providers::tpm] psa_destroy_key ingress
2021-03-04T11:26:43.2098393Z [TRACE parsec_service::back::backend_handler] psa_destroy_key egress
2021-03-04T11:26:43.2099081Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T11:26:43.2099772Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T11:26:43.2100509Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T11:26:43.2101134Z [TRACE parsec] handle_request egress
2021-03-04T11:26:43.2105331Z make: Leaving directory '/tmp/parsec-se-driver/ci/c-tests'
2021-03-04T11:26:45.4179023Z Cleaning up orphan processes
```

**Comment by hug-dev** [comment]
Modifying Mbed TLS version to reproduce #18 and check if CI then fails

**Comment by hug-dev** [comment]
And the failing log, showing that the check works:
```
2021-03-04T12:10:33.0906772Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T12:10:33.0908390Z [INFO  parsec_service::front::front_end] New request received without authentication
2021-03-04T12:10:33.0910147Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T12:10:33.0911734Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T12:10:33.0913206Z [TRACE parsec_service::providers::core] list_authenticators ingress
2021-03-04T12:10:33.0914588Z [TRACE parsec_service::back::backend_handler] list_authenticators egress
2021-03-04T12:10:33.0916045Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T12:10:33.0917807Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T12:10:33.0918788Z [INFO  parsec_service::front::front_end] Response sent back from request without authentication
2021-03-04T12:10:33.0919580Z [TRACE parsec] handle_request egress
2021-03-04T12:10:33.1010104Z [TRACE parsec_service::front::front_end] handle_request ingress
2021-03-04T12:10:33.1011035Z [INFO  parsec_service::front::front_end] New request received from application name "0"
2021-03-04T12:10:33.1012246Z [TRACE parsec_service::back::dispatcher] dispatch_request ingress
2021-03-04T12:10:33.1013105Z [TRACE parsec_service::back::backend_handler] execute_request ingress
2021-03-04T12:10:33.1014163Z [TRACE parsec_service::providers::core] list_providers ingress
2021-03-04T12:10:33.1014943Z [TRACE parsec_service::back::backend_handler] list_providers egress
2021-03-04T12:10:33.1015748Z [TRACE parsec_service::back::dispatcher] execute_request egress
2021-03-04T12:10:33.1016520Z [TRACE parsec_service::front::front_end] dispatch_request egress
2021-03-04T12:10:33.1017338Z [INFO  parsec_service::front::front_end] Response for application name "0" sent back
2021-03-04T12:10:33.1018025Z [TRACE parsec] handle_request egress
2021-03-04T12:10:33.1107988Z make: Leaving directory '/tmp/parsec-se-driver/ci/c-tests'
2021-03-04T12:10:34.8504996Z ##[error]Process completed with exit code 1.
```

**Comment by hug-dev** [comment]
Removing the last commit to merge hte PR.

**Review by ionut-arm — APPROVED** [review]

**Pull request merged**
